### ISSUE TITLE
Transtition from Compound State also Exits and Enters Again Unaffected Parallel or Parent States

### ISSUE THREAD

**Issue by fabb** [jroxendal/PySCXML#4]
For a test project + trace see https://gist.github.com/fabb/5019653

**Comment by jroxendal** [comment]
this is actually the expected behavior. the reason is that since the transition taken at p1x causes P1 to be exited, all children of the parallel state are exited (this is the semantics of a parallel block -- it's always **in** all of it's children concurrently. so this causes a chain reaction of the children of the parallel block being exited. since the target of the transition is again inside the parallel block, it's reentered as a result. 

try setting `type="internal"` on that transition, i think that's what you're looking for. you can also wrap the content of P1 with wrapper state to get the same behavior.

**Comment by fabb** [comment]
Thanks for looking into this.

Ok, I get the part with 'external' vs 'internal' according to section `'Type' and Transitions` in http://www.w3.org/TR/scxml/#CoreIntroduction
This explains for me, why P1 is exited and entered again.

But I do not get why P2 is involved when it's running in parallel.

What is the LCCA in this case? As far as I have read, the `<parallel>` element is also a state. Let's call it P. I think, P is the LCCA, no? But the LCCA should not be exited & entered from a transition, right? So also the other active parallel children of P, namely P2 should not be affected.
Adding `<onentry>` and `<onexit>` to P also shows that P is exited and entered again too.
I do not quite get it. Are you sure the library behaves correctly?
